todo/todo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from todoapp import views


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^todoapp/', include('todoapp.urls')),
    url(r'^index/$', views.index, name='index'),
    url(r'^$', views.Coaches, name='Coaches'),
    url(r'^special/', views.special, name='special'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^addtodo', views.addtodo),
    url(r'^messages/', include('postman.urls')),
]

todo/todoapp/urls.py
from django.conf.urls import url
from todoapp import views


app_name = 'todoapp'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^addtodo/$', views.addtodo),
    url(r'^$', views.Coaches, name='Coaches'),
]

todo/todoapp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
import datetime


class User(AbstractBaseUser):
    Name = models.CharField(max_length=40)
    email = models.EmailField(_('email address'), unique=True)
    password = models.CharField(max_length=20)
    is_active = models.BooleanField(_('active'), default=True)
    created_on = models.DateTimeField(default=datetime.datetime.utcnow)

    REQUIRED_FIELDS = ('Name', 'password')
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'tododemo'


class Todolist(models.Model):
    taskname = models.CharField(max_length=120)
    status = models.CharField(max_length=120, default='active')

    def _str_(self):
        return self.taskname

todo/todoapp/forms.py
from django import forms
##from django.contrib.auth.models import User
from todoapp.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('Name', 'email', 'password')

todo/todoapp/views.py
from django.shortcuts import render
from todoapp.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, get_user_model

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from todoapp.models import Todolist
import json


def Coaches(request):
    return render(request, 'Coaches.html')


def index(request):
    return render(request, 'index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Coaches'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'registration.html',
                  {'user_form': user_form,
                   'registered': registered})


def user_login(request):

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                if user.is_active:
                    return HttpResponse("Your account was inactive.")
        except:
            print("Someone tried to login and failed.")
            print("They used email: {} and password: {}".format(email, password))
            return HttpResponse("Invalid login details given")

    return render(request, 'login.html', {})


@api_view(['GET', 'POST'])
def addtodo(request):
    if request.method == 'POST':
        login_details = json.loads(request.body)
        print(login_details)
        id = login_details.get('id', None)
        taskname = login_details.get('taskname', None)
        print(taskname)
        status1 = login_details.get('status', None)
        todo = Todolist()
        todo.taskname = taskname
        todo.status = status1
        print('****')
        print(todo.status)
        print(todo.taskname)
        print('****')
        import pdb; pdb.set_trace()
        todo.save()

    return Response({'key': 'value'}, status=status.HTTP_200_OK)

todo/todoapp/templates/Coaches.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h2>Welcome to the Jane.. !</h2>
        <h3
                {% if user.is_authenticated %}
        <h2>Hello {{ user.email }}</h2>
        <li><a class="navbar-brand" href="{% url 'index' %}">
        {% else %}
        <h2>Register or Login if you'd like to</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

todo/todoapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'Coaches' %}">DJANGO</a></li>

            <li><a class="navbar-link" href="{% url 'todoapp:register' %}">Register</a></li>
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'todoapp:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

todo/todoapp/templates/index.html
<!doctype html>
{% load static %}
<html lang="en" data-framework="javascript">
	<head>
		<meta charset="utf-8">
		<title>VanillaJS • TodoMVC</title>
		<link rel="stylesheet" href="{% static 'node_modules/todomvc-common/base.css' %}">
		<link rel="stylesheet" href="{% static 'node_modules/todomvc-app-css/index.css' %}">
	</head>
	<body>
		<section class="todoapp">
			<header class="header">
				<h1>todos</h1>
				<input class="new-todo" placeholder="What needs to be done?" autofocus>
			</header>
			<section class="main">
				<input id="toggle-all" class="toggle-all" type="checkbox">
				<label for="toggle-all">Mark all as complete</label>
				<ul class="todo-list"></ul>
			</section>
			<footer class="footer">
				<span class="todo-count"></span>
				<ul class="filters">
					<li>
						<a href="#/" class="selected">All</a>
					</li>
					<li>
						<a href="#/active">Active</a>
					</li>
					<li>
						<a href="#/completed">Completed</a>
					</li>
				</ul>
				<button class="clear-completed">Clear completed</button>
			</footer>
		</section>
		<footer class="info">
			<p>Double-click to edit a todo</p>
			<p>Created by <a href="http://twitter.com/oscargodson">Oscar Godson</a></p>
			<p>Refactored by <a href="https://github.com/cburgmer">Christoph Burgmer</a></p>
			<p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
		</footer>
		<script type="text/javascript" src="{% static 'node_modules/todomvc-common/base.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/helpers.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/store.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/model.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/template.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/view.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/controller.js' %}"></script>
	    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
	</body>
</html>

todo/todoapp/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<center>
  <div class="container">
    <div class="jumbotron">
      <h2>Login</h2><br><br>


        <form method="post" action="{% url 'todoapp:user_login' %}">
        <table>
            <tr>{% csrf_token %}</tr>
            <tr>{# A more "HTML" way of creating the login form#}</tr>
            <tr><label for="email">User email:&nbsp&nbsp</label></tr>
            <tr><input type="text" name="email" placeholder="user email"/></tr><br><br>
            <tr><label for="password">Password:&nbsp&nbsp</label></tr>
            <tr><input type="password" name="password" placeholder="Password"/></tr><br><br>
            <tr><input type="submit" name="" value="Login"></tr>

        </table>
        </form>
</div>
  </div>
    </center>
{% endblock %}

todo/todoapp/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h3>Register Here</h3>
        <h6>Just fill out the form.</h6>
<form enctype="multipart/form-data" method="POST">
                  {% csrf_token %}
          {{ user_form.as_p }}

          <input type="submit" name="" value="Register">

        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}